### ISSUE TITLE
Probleme conveyer

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC-2020-2021#46]
Este scurt si este prea departat de intake, unde cad inelele

**Comment by matei8** [comment]
In cazul asta o sa renuntam la al doilea ax  de la intake (cel dinspre conveyer) si sa prelungim tuburile pana pe el, si probabil sa dam axul respectiv putin mai jos ca sa ni fie probleme dinspre intake spre conveyer la preluarea inelului

**Comment by MihaiBobeica** [comment]
Cu aceste schimbări ar trebui și să schimbăm unghiul pe care îl face conveyer cu solul (să îl ducem de la 30° actual la 42° «unghiul râmpii»)

**Comment by matei8** [comment]
> Cu aceste schimbări ar trebui și să schimbăm unghiul pe care îl face conveyer cu solul (să îl ducem de la 30° actual la 42° «unghiul râmpii»)

Daca facem asta o sa intre in C Channel-ul de mijloc de la Drivetrain

**Comment by matei8** [comment]
O sa dam putin mai in spate al doilea ax ca sa nu fie diferenta prea mare de unghi cand trece de la intake la conveyer

**Comment by matei8** [comment]
![image](https://user-images.githubusercontent.com/73193029/118282803-56abcc80-b4d7-11eb-9814-fd79e0adb3cf.jpeg)
