### ISSUE TITLE
Probleme Brat Wobble

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC-2020-2021#48]
Este usor instabil, iar clestele nu este foarte eficient

**Comment by Andrei-Iatagan** [comment]
<p>pentru a fi mai usor de controlat, propun limitarea miscarii bratului la 90 grade, perpendicular pe pamant</p>

**Comment by matei8** [comment]
Zic sa facem doua brate mobile actionate tot de un servo pt ca ar apuca bratul mai bine si ar fi mult mai usor de controlat. Cand il ridicam cu bratul asta de acum, fiind foarte lung este o sansa mare ca piesa printata sa se rupa din cauza faptului ca elementul de joc tinde sa se miste in laterale, dezecilibrandu-se
