### ISSUE TITLE
Battery Tray

### ISSUE THREAD

**Issue by NegruAdam** [Sova-Tech/FTC-2020-2021#49]
Cum facem un sertar pentru baterie pe care sa il putem trage pentru a schimba bateria fara sa ne incurce plexiglas-ul?

**Comment by matei8** [comment]
Putem sa facem niste piese care se monteaza pe cele doua extrusionuri, si intre ele o placa ca un raft pe care sa stea bateria si sa fie si sus si jos

**Comment by MihaiBobeica** [comment]
Totuși ar trebui sa ridicam destul de mult în sus ca să putem folosi o șurubelniță (nu o cheie)

**Comment by matei8** [comment]
Pai o data montat acolo ramane si nu o sa mai fie nevoie sa o desurubam

**Comment by matei8** [comment]
Ideea acestui "sertar" este sa nu mai trebuiasca sa folosim suruburi, o sa se puna bateria in sertar, care se inchide cu o usita or anything si dupa se conecteaza la switch. Nu o sa fie nevoie de suruburi
